from dataclasses import dataclass


@dataclass
class TrainSettings:
    preset: str
    model_name: str
    model_preset: str
    objective: str
    vocab_size: int
    sequence_len: int
    layers: int
    hidden_size: int
    heads: int
    kv_heads: int
    ffn_size: int
    dropout: float
    learning_rate: float
    weight_decay: float
    beta1: float
    beta2: float
    eps: float
    lr_schedule: str
    warmup_steps: int
    lr_min_factor: float
    gradient_checkpointing: bool
    activation_checkpoint: str
    activation_checkpoint_every_n: int
    checkpoint_preserve_rng: bool
    batch_size: int
    gradient_accumulation: int
    batch_policy: str
    auto_batch: bool
    auto_batch_max: int
    target_effective_batch_tokens: int
    max_optimizer_steps: int
    max_microsteps: int
    max_steps: int
    validate_every_optimizer_steps: int
    save_every_optimizer_steps: int
    intermediate_save_every_optimizer_steps: int
    keep_last_checkpoints: int
    save_latest_every_optimizer_steps: int
    checkpoint_resume_source: str
    log_every_optimizer_steps: int
    validation_batches: int
    resume: str
    amp: str
    compile: str
    compile_warmup_microsteps: int
    static_shapes: bool
    attention_backend: str
    export_checkpoint: str
    fixed_eval_threshold: float
    behavioral_threshold: float
    enforce_competency: bool
    corpus_size: int
    corpus_tokens: int
    corpus_dir: str
    curriculum: str
    seed: int
    data_mode: str
    dataloader_impl: str
    num_workers: int
    pin_memory: bool
    prefetch_factor: int
    persistent_workers: bool
    allow_tf32: bool
    matmul_precision: str
    clip_grad_norm: float
    profile_steps: int
    benchmark_warmup_microsteps: int
    dataloader_benchmark: bool
