#!/usr/bin/env python3
from pathlib import Path
import sys

sys.path[:0] = [str(Path(__file__).resolve().parent), "/usr/local/lib"]

from public_pretrain.cli import main

if __name__ == "__main__":
    main()
