set(LKJAI_CUDA_SOURCES
  src/cuda_probe.cu
  src/runtime_errors.cu
  src/runtime_context.cu
  src/runtime_device.cu
  src/runtime_workspace.cu
  src/dense_cuda_tuning.cpp
)

set(LKJAI_NATIVE_CORE_SOURCES
  src/artifact.cpp
  src/artifact_manifest.cpp
  src/artifact_validate.cpp
  src/capability_json.cpp
  src/decoder_chat_request.cpp
  src/decoder_decode.cpp
  src/decoder_kv_cache.cpp
  src/decoder_cuda_block.cu
  src/decoder_cuda_block_probe.cpp
  src/decoder_cuda_block_project.cu
  src/decoder_cuda_block_shape.cpp
  src/decoder_cuda_norm.cu
  src/decoder_cuda_residual.cu
  src/decoder_cuda_slice_block.cpp
  src/decoder_cuda_slice.cpp
  src/decoder_cuda_slice_util.cpp
  src/dense_checkpoint.cpp
  src/dense_cuda.cu
  src/dense_cuda_common.cpp
  src/dense_cuda_gemm.cu
  src/dense_cuda_kernels.cu
  src/dense_cuda_logits.cpp
  src/dense_cuda_logits_reference.cpp
  src/dense_cuda_report.cpp
  src/dense_cuda_state.cu
  src/dense_cuda_step.cu
  src/dense_cuda_train.cpp
  src/dense_loss_trend.cpp
  src/dense_model.cpp
  src/dense_report_util.cpp
  src/dense_train.cpp
  src/dense_train_artifact.cpp
  src/dense_train_math.cpp
  src/dense_weight_change.cpp
  src/env.cpp
  src/json_min.cpp
  src/native_chat_prompt.cpp
  src/native_chat_prompt_serialize.cpp
  src/native_server_routes.cpp
  src/native_status_page.cpp
  src/native_tokenizer.cpp
  src/native_tokenizer_codec.cpp
  src/native_tokenizer_json.cpp
  src/native_http_client.cpp
  src/packed_cache.cpp
  src/packed_cache_build.cpp
  src/packed_cache_digest.cpp
  src/packed_cache_reader.cpp
  src/packed_cache_validate.cpp
  src/runtime_api.cpp
  src/runtime_config_status.cpp
  src/runtime_events.cpp
  src/train_data.cpp
  src/train_real.cpp
  src/train_report.cpp
  src/training_config.cpp
  src/transformer_artifact.cpp
  src/transformer_config.cpp
  src/transformer_cuda.cu
  src/transformer_forward.cpp
  src/transformer_init.cpp
  src/transformer_load.cpp
  src/transformer_logits.cpp
  src/transformer_optim.cpp
  src/transformer_report.cpp
  src/transformer_report_acceptance.cpp
  src/transformer_report_io.cpp
  src/transformer_train.cpp
  src/transformer_util.cpp
)
