#pragma once

namespace lkjai {

struct NativeXmlTag {
  const char* text;
  bool special;
};

inline constexpr NativeXmlTag kNativeXmlTags[] = {
    {"<pad>", true},
    {"<unk>", true},
    {"<bos>", true},
    {"<eos>", true},
    {"<assistant_action>", true},
    {"<dialogue>", false},
    {"</dialogue>", false},
    {"<message>", false},
    {"</message>", false},
    {"<role>", false},
    {"</role>", false},
    {"<tool_name>", false},
    {"</tool_name>", false},
    {"<content>", false},
    {"</content>", false},
    {"<run>", false},
    {"</run>", false},
    {"<run_id>", false},
    {"</run_id>", false},
    {"<step>", false},
    {"</step>", false},
    {"<summary>", false},
    {"</summary>", false},
    {"<memories>", false},
    {"</memories>", false},
    {"<events>", false},
    {"</events>", false},
    {"<event>", false},
    {"</event>", false},
    {"<kind>", false},
    {"</kind>", false},
    {"<task>", false},
    {"</task>", false},
    {"<request>", false},
    {"</request>", false},
    {"<context>", false},
    {"</context>", false},
    {"<constraints>", false},
    {"</constraints>", false},
    {"<action>", false},
    {"</action>", false},
    {"<reasoning>", false},
    {"</reasoning>", false},
    {"<tool>", false},
    {"</tool>", false},
    {"<path>", false},
    {"</path>", false},
    {"<query>", false},
    {"</query>", false},
    {"<command>", false},
    {"</command>", false},
    {"<url>", false},
    {"</url>", false},
    {"<operation>", false},
    {"</operation>", false},
    {"<pending_tool>", false},
    {"</pending_tool>", false},
    {"<ref>", false},
    {"</ref>", false},
    {"<id>", false},
    {"</id>", false},
    {"<body>", false},
    {"</body>", false},
    {"<is_private>", false},
    {"</is_private>", false},
    {"<is_favorite>", false},
    {"</is_favorite>", false},
    {"<current_resource_id>", false},
    {"</current_resource_id>", false},
    {"<alias>", false},
    {"</alias>", false},
    {"<case>", false},
    {"</case>", false},
    {"<schema>", false},
    {"</schema>", false},
    {"<scenario>", false},
    {"</scenario>", false},
    {"<skill>", false},
    {"</skill>", false},
    {"<source>", false},
    {"</source>", false},
    {"<title>", false},
    {"</title>", false},
    {"<snippet>", false},
    {"</snippet>", false},
    {"<angle>", false},
    {"</angle>", false},
    {"<audience>", false},
    {"</audience>", false},
    {"<policy>", false},
    {"</policy>", false},
    {"<first>", false},
    {"</first>", false},
    {"<error>", false},
    {"</error>", false},
    {"<blocker>", false},
    {"</blocker>", false},
    {"<draft>", false},
    {"</draft>", false},
    {"<session>", false},
    {"</session>", false},
    {"<mode>", false},
    {"</mode>", false},
    {"<args>", false},
    {"</args>", false},
};

}  // namespace lkjai
